local_repository(
  # Name of the Abseil repository. This name is defined within Abseil's
  # WORKSPACE file, in its `workspace()` metadata
  name = "com_google_absl",

  # NOTE: Bazel paths must be absolute paths. E.g., you can't use ~/Source
  #path = "/PATH_TO_SOURCE/Source/abseil-cpp",
  path = "c:/home/github/bazel/source/abseil-cpp",
)